CREATE TABLE [dbo].[Area]
(
	AreaID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	AreaName NVARCHAR(510) NOT NULL,
	LocationID INT NOT NULL REFERENCES Location(LocationID),
	Valid BIT NOT NULL DEFAULT(1)
)
