CREATE TABLE GlobalSettings
(
	GlobalSettingID INT IDENTITY(1,1) PRIMARY KEY,
	SiteID			INT NOT NULL REFERENCES Sites(SiteID),
	DefaultLanguageID INT NOT NULL REFERENCES Languages(LanguageID) DEFAULT(1),
	DefaultDynamicPageID INT REFERENCES DynamicPages(DynamicPageID),
	PublicJobsSearch BIT DEFAULT(0) NOT NULL,
	PublicMembersSearch BIT DEFAULT(0) NOT NULL,
	PublicCompaniesSearch BIT DEFAULT(0) NOT NULL,
	PublicSponsoredAdverts BIT DEFAULT(0) NOT NULL,
	PrivateJobs BIT DEFAULT(0) NOT NULL,
	PrivateMembers BIT DEFAULT(0) NOT NULL,
	PrivateCompanies BIT DEFAULT(0) NOT NULL,
	LastModifiedBy INT NOT NULL REFERENCES AdminUsers(AdminUserID),
	LastModified DATETIME DEFAULT(GETDATE()) NOT NULL,
	PageTitlePrefix VARCHAR(255),
	PageTitleSuffix VARCHAR(255),
	DefaultTitle VARCHAR(255),
	HomeTitle VARCHAR(255),
	DefaultDescription VARCHAR(255),
	HomeDescription VARCHAR(255),
	DefaultKeywords VARCHAR(255),
	HomeKeywords VARCHAR(255),
	ShowFaceBookButton BIT NOT NULL DEFAULT(0),
	UseAdvertiserFilter INT DEFAULT(0) NOT NULL,
	MerchantID INT,
	ShowTwitterButton BIT DEFAULT(0) NOT NULL,
	ShowJobAlertButton BIT DEFAULT(0) NOT NULL,
	ShowLinkedInButton BIT DEFAULT(0) NOT NULL,
	SiteFavIconID	INT REFERENCES Files(FileID),
	SiteDocType		VARCHAR(512),
	CurrencySymbol VARCHAR(10),
	FTPFolderLocation VARCHAR(255),
	MetaTags VARCHAR(2000),  
	SystemMetaTags VARCHAR(2000)
)
GO