CREATE TABLE [dbo].[JobAlerts]
(
	[JobAlertID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[JobAlertName] [NVARCHAR](510) NULL,
	[LastModified] DATETIME NOT NULL DEFAULT(GETDATE()),
	[SearchKeywords] [varchar](1000) NULL,
	[RecurrenceType] [int] NULL,
	[DailyFrequency] [int] NULL,
	[WeeklyFrequency] [int] NULL,
	[WeeklyDayOccurence] [int] NULL,
	[DateLastRun] [datetime] NULL,
	[DateNextRun] [datetime] NULL,
	[MemberID] [int] NOT NULL REFERENCES Members(MemberID),
	[AlertActive] [bit] NULL,
	[EmailFormat] [int] NULL,
	[CustomRecurrenceType] [int] NULL, 
	[LastResultCount] [int] NULL,
	[PrimaryAlert] [bit] NULL DEFAULT ((0)),
	[UnsubscribeValidateID] [uniqueidentifier] NULL,
	[EditValidateID] [uniqueidentifier] NULL,
	[ViewValidateID] [uniqueidentifier] NULL,
	[SiteID] [int] NOT NULL REFERENCES Sites(SiteID),
	[CountryId] [int] NOT NULL REFERENCES Countries(CountryID),
	[LocationID] [int] NULL REFERENCES Location(LocationID),
	[AreaIDs] [varchar](255) NULL,
	[ProfessionID] [int] NULL REFERENCES Profession(ProfessionID),
	[SearchRoleIDs] [varchar](500) NULL,
	[WorkTypeIDs] [varchar](100) NULL,
	[SalaryIDs] [varchar](50) NULL,
	[DaysPosted] [int] NULL,
	[GeneratedSQL] [varchar] (8000) NULL
)
