CREATE TABLE [dbo].[JobRoles]
(
	JobRoleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	JobID INT NULL REFERENCES Jobs(JobID),
	JobArchiveID INT NULL REFERENCES JobsArchive(JobID),
	RoleID INT NULL REFERENCES Roles(RoleID)
)
