CREATE TABLE [dbo].[JobViews]
(
	JobViewID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SiteID INT NOT NULL REFERENCES Sites(SiteID),
	JobID INT NULL REFERENCES Jobs(JobID),
	JobArchiveID INT NULL REFERENCES JobsArchive(JobID),
	ViewDate SMALLDATETIME NOT NULL,
	TotalView INT NOT NULL DEFAULT(0)
)
