CREATE TABLE [dbo].[SiteArea]
(
	SiteAreaID INT PRIMARY KEY IDENTITY(1,1),
	SiteID INT NOT NULL REFERENCES Sites(SiteID),
	AreaID INT NOT NULL REFERENCES Area(AreaID),
	SiteAreaName NVARCHAR(510) NOT NULL,
	Valid BIT NOT NULL DEFAULT(1)
)
