CREATE TABLE [dbo].[WidgetContainers]
(
	  [WidgetID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
      [SiteID] [int] REFERENCES Sites(SiteId) NOT NULL,
      [LanguageID] [int] REFERENCES Languages(LanguageId) NOT NULL,
      [WidgetName] [varchar](255) ,
      [WidgetDomain] [varchar](255) ,
      [WidgetContainerClass] [varchar](255) ,
      [WidgetContainerHeaderClass] [varchar](255) ,
      [WidgetItemClass] [varchar](255) ,
      [WidgetJobLinkCSS] [varchar](255) ,
      [WidgetItemLinkImageID] [int] NULL,
      [Valid] [bit] NULL DEFAULT ((1)),
      [ShowJobs] [bit] NULL DEFAULT ((1)),
      [ShowCompanies] [bit] NULL DEFAULT ((0)),
      [ShowSite] [bit] NULL DEFAULT ((0)),
      [ShowPeople] [bit] NULL DEFAULT ((0)),
      [JobHtml] NVARCHAR(max) ,
      [CompanyHtml] NVARCHAR(max) ,
      [SiteHtml] NVARCHAR(max) ,
      [PeopleHtml] NVARCHAR(max) ,
      [Javascript] [varchar](max) ,
      [SearchCSS] [varchar](max) ,
      [DefaultProfessionID] [int] NULL REFERENCES Profession(ProfessionId),
      [DefaultCountryID] [int] NULL REFERENCES Countries(CountryId),
      [DefaultLocationID] [int] NULL REFERENCES Location(LocationId),
      [Width] [int] NULL DEFAULT ((0)),
      [Height] [int] NULL DEFAULT ((0)),
	  [OnAdvancedSearch] [bit] NULL DEFAULT ((0))
)
