using System;
using System.ComponentModel;

namespace JXTPortal.Entities
{
	/// <summary>
	///		The data structure representation of the 'AdvertiserUsers' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAdvertiserUsers 
	{
		/// <summary>			
		/// AdvertiserUserID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "AdvertiserUsers"</remarks>
		System.Int32 AdvertiserUserId { get; set; }
				
		
		
		/// <summary>
		/// AdvertiserID : 
		/// </summary>
		System.Int32  AdvertiserId  { get; set; }
		
		/// <summary>
		/// PrimaryAccount : 
		/// </summary>
		System.Boolean  PrimaryAccount  { get; set; }
		
		/// <summary>
		/// UserName : 
		/// </summary>
		System.String  UserName  { get; set; }
		
		/// <summary>
		/// UserPassword : 
		/// </summary>
		System.String  UserPassword  { get; set; }
		
		/// <summary>
		/// FirstName : 
		/// </summary>
		System.String  FirstName  { get; set; }
		
		/// <summary>
		/// Surname : 
		/// </summary>
		System.String  Surname  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// ApplicationEmailAddress : 
		/// </summary>
		System.String  ApplicationEmailAddress  { get; set; }
		
		/// <summary>
		/// Phone : 
		/// </summary>
		System.String  Phone  { get; set; }
		
		/// <summary>
		/// Fax : 
		/// </summary>
		System.String  Fax  { get; set; }
		
		/// <summary>
		/// AccountStatus : 
		/// </summary>
		System.Int32?  AccountStatus  { get; set; }
		
		/// <summary>
		/// Newsletter : 
		/// </summary>
		System.Boolean  Newsletter  { get; set; }
		
		/// <summary>
		/// NewsletterFormat : 
		/// </summary>
		System.Int32  NewsletterFormat  { get; set; }
		
		/// <summary>
		/// EmailFormat : 
		/// </summary>
		System.Int32  EmailFormat  { get; set; }
		
		/// <summary>
		/// Validated : 
		/// </summary>
		System.Boolean?  Validated  { get; set; }
		
		/// <summary>
		/// ValidateGUID : 
		/// </summary>
		System.Guid?  ValidateGuid  { get; set; }
		
		/// <summary>
		/// Description : 
		/// </summary>
		System.String  Description  { get; set; }
		
		/// <summary>
		/// LastLoginDate : 
		/// </summary>
		System.DateTime?  LastLoginDate  { get; set; }
		
		/// <summary>
		/// LastModified : 
		/// </summary>
		System.DateTime?  LastModified  { get; set; }
		
		/// <summary>
		/// LastModifiedBy : 
		/// </summary>
		System.Int32  LastModifiedBy  { get; set; }
		
		/// <summary>
		/// JobExpiryNotification : 
		/// </summary>
		System.Boolean  JobExpiryNotification  { get; set; }
		
		/// <summary>
		/// LoginAttempts : 
		/// </summary>
		System.Int32  LoginAttempts  { get; set; }
		
		/// <summary>
		/// LastAttemptDate : 
		/// </summary>
		System.DateTime?  LastAttemptDate  { get; set; }
		
		/// <summary>
		/// Status : 
		/// </summary>
		System.Int32  Status  { get; set; }
		
		/// <summary>
		/// LastTermsAndConditionsDate : 
		/// </summary>
		System.DateTime?  LastTermsAndConditionsDate  { get; set; }
		
		/// <summary>
		/// DefaultLanguageId : 
		/// </summary>
		System.Int32?  DefaultLanguageId  { get; set; }
		
		/// <summary>
		/// ExternalAdvertiserUserID : 
		/// </summary>
		System.String  ExternalAdvertiserUserId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _jobApplicationNotesAdvertiserUserId
		/// </summary>	
		TList<JobApplicationNotes> JobApplicationNotesCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _invoiceItemAdvertiserUserId
		/// </summary>	
		TList<InvoiceItem> InvoiceItemCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _jobsLastModifiedByAdvertiserUserId
		/// </summary>	
		TList<Jobs> JobsCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _invoiceOrderAdvertiserUserId
		/// </summary>	
		TList<InvoiceOrder> InvoiceOrderCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _invoiceAdvertiserUserId
		/// </summary>	
		TList<Invoice> InvoiceCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _jobsArchiveLastModifiedByAdvertiserUserId
		/// </summary>	
		TList<JobsArchive> JobsArchiveCollection {  get;  set;}	

		#endregion Data Properties

	}
}


