using System;
using System.ComponentModel;

namespace JXTPortal.Entities
{
	/// <summary>
	///		The data structure representation of the 'EmailFormats' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IEmailFormats 
	{
		/// <summary>			
		/// EmailFormatID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "EmailFormats"</remarks>
		System.Int32 EmailFormatId { get; set; }
				
		
		
		/// <summary>
		/// EmailFormatName : 
		/// </summary>
		System.String  EmailFormatName  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _membersEmailFormat
		/// </summary>	
		TList<Members> MembersCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _advertiserUsersNewsletterFormatGetByEmailFormat
		/// </summary>	
		TList<AdvertiserUsers> AdvertiserUsersCollectionGetByEmailFormat {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _advertiserUsersNewsletterFormatGetByNewsletterFormat
		/// </summary>	
		TList<AdvertiserUsers> AdvertiserUsersCollectionGetByNewsletterFormat {  get;  set;}	

		#endregion Data Properties

	}
}


