
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file MemberLanguages.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using JXTPortal.Entities.Validation;
#endregion

namespace JXTPortal.Entities
{
	///<summary>
	/// An object representation of the 'MemberLanguages' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class MemberLanguagesBase : EntityBase, IMemberLanguages, IEntityId<MemberLanguagesKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private MemberLanguagesEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private MemberLanguagesEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private MemberLanguagesEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<MemberLanguages> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MemberLanguagesEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MemberLanguagesEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="MemberLanguagesBase"/> instance.
		///</summary>
		public MemberLanguagesBase()
		{
			this.entityData = new MemberLanguagesEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="MemberLanguagesBase"/> instance.
		///</summary>
		///<param name="_memberId"></param>
		///<param name="_langauges"></param>
		///<param name="_profieciency"></param>
		///<param name="_lastModifiedDate"></param>
		public MemberLanguagesBase(System.Int32? _memberId, System.String _langauges, System.Int32? _profieciency, 
			System.DateTime? _lastModifiedDate)
		{
			this.entityData = new MemberLanguagesEntityData();
			this.backupData = null;

			this.MemberId = _memberId;
			this.Langauges = _langauges;
			this.Profieciency = _profieciency;
			this.LastModifiedDate = _lastModifiedDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="MemberLanguages"/> instance.
		///</summary>
		///<param name="_memberId"></param>
		///<param name="_langauges"></param>
		///<param name="_profieciency"></param>
		///<param name="_lastModifiedDate"></param>
		public static MemberLanguages CreateMemberLanguages(System.Int32? _memberId, System.String _langauges, System.Int32? _profieciency, 
			System.DateTime? _lastModifiedDate)
		{
			MemberLanguages newMemberLanguages = new MemberLanguages();
			newMemberLanguages.MemberId = _memberId;
			newMemberLanguages.Langauges = _langauges;
			newMemberLanguages.Profieciency = _profieciency;
			newMemberLanguages.LastModifiedDate = _lastModifiedDate;
			return newMemberLanguages;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MemberLanguageId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 MemberLanguageId
		{
			get
			{
				return this.entityData.MemberLanguageId; 
			}
			
			set
			{
				if (this.entityData.MemberLanguageId == value)
					return;
					
				OnColumnChanging(MemberLanguagesColumn.MemberLanguageId, this.entityData.MemberLanguageId);
				this.entityData.MemberLanguageId = value;
				this.EntityId.MemberLanguageId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MemberLanguagesColumn.MemberLanguageId, this.entityData.MemberLanguageId);
				OnPropertyChanged("MemberLanguageId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MemberId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsMemberIdNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? MemberId
		{
			get
			{
				return this.entityData.MemberId; 
			}
			
			set
			{
				if (this.entityData.MemberId == value)
					return;
					
				OnColumnChanging(MemberLanguagesColumn.MemberId, this.entityData.MemberId);
				this.entityData.MemberId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MemberLanguagesColumn.MemberId, this.entityData.MemberId);
				OnPropertyChanged("MemberId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Langauges property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 150)]
		public virtual System.String Langauges
		{
			get
			{
				return this.entityData.Langauges; 
			}
			
			set
			{
				if (this.entityData.Langauges == value)
					return;
					
				OnColumnChanging(MemberLanguagesColumn.Langauges, this.entityData.Langauges);
				this.entityData.Langauges = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MemberLanguagesColumn.Langauges, this.entityData.Langauges);
				OnPropertyChanged("Langauges");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Profieciency property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsProfieciencyNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? Profieciency
		{
			get
			{
				return this.entityData.Profieciency; 
			}
			
			set
			{
				if (this.entityData.Profieciency == value)
					return;
					
				OnColumnChanging(MemberLanguagesColumn.Profieciency, this.entityData.Profieciency);
				this.entityData.Profieciency = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MemberLanguagesColumn.Profieciency, this.entityData.Profieciency);
				OnPropertyChanged("Profieciency");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the LastModifiedDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsLastModifiedDateNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? LastModifiedDate
		{
			get
			{
				return this.entityData.LastModifiedDate; 
			}
			
			set
			{
				if (this.entityData.LastModifiedDate == value)
					return;
					
				OnColumnChanging(MemberLanguagesColumn.LastModifiedDate, this.entityData.LastModifiedDate);
				this.entityData.LastModifiedDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MemberLanguagesColumn.LastModifiedDate, this.entityData.LastModifiedDate);
				OnPropertyChanged("LastModifiedDate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Members"/>.
		/// </summary>
		/// <value>The source Members for MemberId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Members MemberIdSource
      	{
            get { return entityData.MemberIdSource; }
            set { entityData.MemberIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Langauges", "Langauges", 150));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "MemberLanguages"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MemberLanguageID", "MemberID", "Langauges", "Profieciency", "LastModifiedDate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as MemberLanguagesEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (MemberLanguages) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<MemberLanguages>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as MemberLanguages);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed MemberLanguages Entity 
		///</summary>
		protected virtual MemberLanguages Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			MemberLanguages copy = new MemberLanguages();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.MemberLanguageId = this.MemberLanguageId;
				copy.MemberId = this.MemberId;
				copy.Langauges = this.Langauges;
				copy.Profieciency = this.Profieciency;
				copy.LastModifiedDate = this.LastModifiedDate;
			
			if (this.MemberIdSource != null && existingCopies.Contains(this.MemberIdSource))
				copy.MemberIdSource = existingCopies[this.MemberIdSource] as Members;
			else
				copy.MemberIdSource = MakeCopyOf(this.MemberIdSource, existingCopies) as Members;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed MemberLanguages Entity 
		///</summary>
		public virtual MemberLanguages Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed MemberLanguages Entity which is a deep copy of the current entity.
		///</summary>
		public virtual MemberLanguages DeepCopy()
		{
			return EntityHelper.Clone<MemberLanguages>(this as MemberLanguages);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as MemberLanguagesEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new MemberLanguagesEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as MemberLanguagesEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(MemberLanguagesColumn column)
		{
			switch(column)
			{
					case MemberLanguagesColumn.MemberLanguageId:
					return entityData.MemberLanguageId != _originalData.MemberLanguageId;
					case MemberLanguagesColumn.MemberId:
					return entityData.MemberId != _originalData.MemberId;
					case MemberLanguagesColumn.Langauges:
					return entityData.Langauges != _originalData.Langauges;
					case MemberLanguagesColumn.Profieciency:
					return entityData.Profieciency != _originalData.Profieciency;
					case MemberLanguagesColumn.LastModifiedDate:
					return entityData.LastModifiedDate != _originalData.LastModifiedDate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< MemberLanguagesColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MemberLanguageId != _originalData.MemberLanguageId;
			result = result || entityData.MemberId != _originalData.MemberId;
			result = result || entityData.Langauges != _originalData.Langauges;
			result = result || entityData.Profieciency != _originalData.Profieciency;
			result = result || entityData.LastModifiedDate != _originalData.LastModifiedDate;
			return result;
		}	
		
		///<summary>
		///  Returns a MemberLanguages Entity with the original data.
		///</summary>
		public MemberLanguages GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateMemberLanguages(
				_originalData.MemberId,
				_originalData.Langauges,
				_originalData.Profieciency,
				_originalData.LastModifiedDate
				);
				
			return (MemberLanguages)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="MemberLanguagesBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is MemberLanguagesBase)
				return ValueEquals(this, (MemberLanguagesBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="MemberLanguagesBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MemberLanguageId.GetHashCode() ^ 
					((this.MemberId == null) ? string.Empty : this.MemberId.ToString()).GetHashCode() ^ 
					((this.Langauges == null) ? string.Empty : this.Langauges.ToString()).GetHashCode() ^ 
					((this.Profieciency == null) ? string.Empty : this.Profieciency.ToString()).GetHashCode() ^ 
					((this.LastModifiedDate == null) ? string.Empty : this.LastModifiedDate.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="MemberLanguagesBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(MemberLanguagesBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="MemberLanguagesBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="MemberLanguagesBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="MemberLanguagesBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(MemberLanguagesBase Object1, MemberLanguagesBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MemberLanguageId != Object2.MemberLanguageId)
				equal = false;
			if ( Object1.MemberId != null && Object2.MemberId != null )
			{
				if (Object1.MemberId != Object2.MemberId)
					equal = false;
			}
			else if (Object1.MemberId == null ^ Object2.MemberId == null )
			{
				equal = false;
			}
			if ( Object1.Langauges != null && Object2.Langauges != null )
			{
				if (Object1.Langauges != Object2.Langauges)
					equal = false;
			}
			else if (Object1.Langauges == null ^ Object2.Langauges == null )
			{
				equal = false;
			}
			if ( Object1.Profieciency != null && Object2.Profieciency != null )
			{
				if (Object1.Profieciency != Object2.Profieciency)
					equal = false;
			}
			else if (Object1.Profieciency == null ^ Object2.Profieciency == null )
			{
				equal = false;
			}
			if ( Object1.LastModifiedDate != null && Object2.LastModifiedDate != null )
			{
				if (Object1.LastModifiedDate != Object2.LastModifiedDate)
					equal = false;
			}
			else if (Object1.LastModifiedDate == null ^ Object2.LastModifiedDate == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((MemberLanguagesBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static MemberLanguagesComparer GetComparer()
        {
            return new MemberLanguagesComparer();
        }
        */

        // Comparer delegates back to MemberLanguages
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(MemberLanguages rhs, MemberLanguagesColumn which)
        {
            switch (which)
            {
            	
            	
            	case MemberLanguagesColumn.MemberLanguageId:
            		return this.MemberLanguageId.CompareTo(rhs.MemberLanguageId);
            		
            		                 
            	
            	
            	case MemberLanguagesColumn.MemberId:
            		return this.MemberId.Value.CompareTo(rhs.MemberId.Value);
            		
            		                 
            	
            	
            	case MemberLanguagesColumn.Langauges:
            		return this.Langauges.CompareTo(rhs.Langauges);
            		
            		                 
            	
            	
            	case MemberLanguagesColumn.Profieciency:
            		return this.Profieciency.Value.CompareTo(rhs.Profieciency.Value);
            		
            		                 
            	
            	
            	case MemberLanguagesColumn.LastModifiedDate:
            		return this.LastModifiedDate.Value.CompareTo(rhs.LastModifiedDate.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<MemberLanguagesKey> Members
		
		// member variable for the EntityId property
		private MemberLanguagesKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual MemberLanguagesKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new MemberLanguagesKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("MemberLanguages")
					.Append("|").Append( this.MemberLanguageId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- MemberLanguageId: {0}{5}- MemberId: {1}{5}- Langauges: {2}{5}- Profieciency: {3}{5}- LastModifiedDate: {4}{5}{7}", 
				this.MemberLanguageId,
				(this.MemberId == null) ? string.Empty : this.MemberId.ToString(),
				(this.Langauges == null) ? string.Empty : this.Langauges.ToString(),
				(this.Profieciency == null) ? string.Empty : this.Profieciency.ToString(),
				(this.LastModifiedDate == null) ? string.Empty : this.LastModifiedDate.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'MemberLanguages' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class MemberLanguagesEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// MemberLanguageID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "MemberLanguages"</remarks>
		public System.Int32 MemberLanguageId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// MemberID : 
		/// </summary>
		public System.Int32?		  MemberId = null;
		
		/// <summary>
		/// Langauges : 
		/// </summary>
		public System.String		  Langauges = null;
		
		/// <summary>
		/// Profieciency : 
		/// </summary>
		public System.Int32?		  Profieciency = null;
		
		/// <summary>
		/// LastModifiedDate : 
		/// </summary>
		public System.DateTime?		  LastModifiedDate = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Members _memberIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Members"/>.
		/// </summary>
		/// <value>The source Members for MemberId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Members MemberIdSource
      	{
            get { return this._memberIdSource; }
            set { this._memberIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			MemberLanguagesEntityData _tmp = new MemberLanguagesEntityData();
						
			_tmp.MemberLanguageId = this.MemberLanguageId;
			
			_tmp.MemberId = this.MemberId;
			_tmp.Langauges = this.Langauges;
			_tmp.Profieciency = this.Profieciency;
			_tmp.LastModifiedDate = this.LastModifiedDate;
			
			#region Source Parent Composite Entities
			if (this.MemberIdSource != null)
				_tmp.MemberIdSource = MakeCopyOf(this.MemberIdSource) as Members;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			MemberLanguagesEntityData _tmp = new MemberLanguagesEntityData();
						
			_tmp.MemberLanguageId = this.MemberLanguageId;
			
			_tmp.MemberId = this.MemberId;
			_tmp.Langauges = this.Langauges;
			_tmp.Profieciency = this.Profieciency;
			_tmp.LastModifiedDate = this.LastModifiedDate;
			
			#region Source Parent Composite Entities
			if (this.MemberIdSource != null && existingCopies.Contains(this.MemberIdSource))
				_tmp.MemberIdSource = existingCopies[this.MemberIdSource] as Members;
			else
				_tmp.MemberIdSource = MakeCopyOf(this.MemberIdSource, existingCopies) as Members;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MemberLanguagesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(MemberLanguagesColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MemberLanguagesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(MemberLanguagesColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MemberLanguagesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(MemberLanguagesColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				MemberLanguagesEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new MemberLanguagesEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MemberLanguagesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(MemberLanguagesColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				MemberLanguagesEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new MemberLanguagesEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region MemberLanguagesEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="MemberLanguages"/> object.
	/// </remarks>
	public class MemberLanguagesEventArgs : System.EventArgs
	{
		private MemberLanguagesColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the MemberLanguagesEventArgs class.
		///</summary>
		public MemberLanguagesEventArgs(MemberLanguagesColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the MemberLanguagesEventArgs class.
		///</summary>
		public MemberLanguagesEventArgs(MemberLanguagesColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The MemberLanguagesColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="MemberLanguagesColumn" />
		public MemberLanguagesColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all MemberLanguages related events.
	///</summary>
	public delegate void MemberLanguagesEventHandler(object sender, MemberLanguagesEventArgs e);
	
	#region MemberLanguagesComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class MemberLanguagesComparer : System.Collections.Generic.IComparer<MemberLanguages>
	{
		MemberLanguagesColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:MemberLanguagesComparer"/> class.
        /// </summary>
		public MemberLanguagesComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:MemberLanguagesComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public MemberLanguagesComparer(MemberLanguagesColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="MemberLanguages"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="MemberLanguages"/> to compare.</param>
        /// <param name="b">The second <c>MemberLanguages</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(MemberLanguages a, MemberLanguages b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(MemberLanguages entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(MemberLanguages a, MemberLanguages b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public MemberLanguagesColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region MemberLanguagesKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="MemberLanguages"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class MemberLanguagesKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the MemberLanguagesKey class.
		/// </summary>
		public MemberLanguagesKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the MemberLanguagesKey class.
		/// </summary>
		public MemberLanguagesKey(MemberLanguagesBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MemberLanguageId = entity.MemberLanguageId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the MemberLanguagesKey class.
		/// </summary>
		public MemberLanguagesKey(System.Int32 _memberLanguageId)
		{
			#region Init Properties

			this.MemberLanguageId = _memberLanguageId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private MemberLanguagesBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public MemberLanguagesBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MemberLanguageId property
		private System.Int32 _memberLanguageId;
		
		/// <summary>
		/// Gets or sets the MemberLanguageId property.
		/// </summary>
		public System.Int32 MemberLanguageId
		{
			get { return _memberLanguageId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MemberLanguageId = value;
				
				_memberLanguageId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MemberLanguageId = ( values["MemberLanguageId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["MemberLanguageId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MemberLanguageId", MemberLanguageId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MemberLanguageId: {0}{1}",
								MemberLanguageId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region MemberLanguagesColumn Enum
	
	/// <summary>
	/// Enumerate the MemberLanguages columns.
	/// </summary>
	[Serializable]
	public enum MemberLanguagesColumn : int
	{
		/// <summary>
		/// MemberLanguageId : 
		/// </summary>
		[EnumTextValue("MemberLanguageID")]
		[ColumnEnum("MemberLanguageID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		MemberLanguageId = 1,
		/// <summary>
		/// MemberId : 
		/// </summary>
		[EnumTextValue("MemberID")]
		[ColumnEnum("MemberID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		MemberId = 2,
		/// <summary>
		/// Langauges : 
		/// </summary>
		[EnumTextValue("Langauges")]
		[ColumnEnum("Langauges", typeof(System.String), System.Data.DbType.String, false, false, true, 150)]
		Langauges = 3,
		/// <summary>
		/// Profieciency : 
		/// </summary>
		[EnumTextValue("Profieciency")]
		[ColumnEnum("Profieciency", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		Profieciency = 4,
		/// <summary>
		/// LastModifiedDate : 
		/// </summary>
		[EnumTextValue("LastModifiedDate")]
		[ColumnEnum("LastModifiedDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		LastModifiedDate = 5
	}//End enum

	#endregion MemberLanguagesColumn Enum

} // end namespace
