
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file SiteCustomMapping.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using JXTPortal.Entities.Validation;
#endregion

namespace JXTPortal.Entities
{
	///<summary>
	/// An object representation of the 'SiteCustomMapping' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class SiteCustomMappingBase : EntityBase, ISiteCustomMapping, IEntityId<SiteCustomMappingKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private SiteCustomMappingEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private SiteCustomMappingEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private SiteCustomMappingEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<SiteCustomMapping> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SiteCustomMappingEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SiteCustomMappingEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="SiteCustomMappingBase"/> instance.
		///</summary>
		public SiteCustomMappingBase()
		{
			this.entityData = new SiteCustomMappingEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="SiteCustomMappingBase"/> instance.
		///</summary>
		///<param name="_siteId"></param>
		///<param name="_masterSiteId"></param>
		public SiteCustomMappingBase(System.Int32 _siteId, System.Int32 _masterSiteId)
		{
			this.entityData = new SiteCustomMappingEntityData();
			this.backupData = null;

			this.SiteId = _siteId;
			this.MasterSiteId = _masterSiteId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="SiteCustomMapping"/> instance.
		///</summary>
		///<param name="_siteId"></param>
		///<param name="_masterSiteId"></param>
		public static SiteCustomMapping CreateSiteCustomMapping(System.Int32 _siteId, System.Int32 _masterSiteId)
		{
			SiteCustomMapping newSiteCustomMapping = new SiteCustomMapping();
			newSiteCustomMapping.SiteId = _siteId;
			newSiteCustomMapping.MasterSiteId = _masterSiteId;
			return newSiteCustomMapping;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the SiteCustomMappingId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 SiteCustomMappingId
		{
			get
			{
				return this.entityData.SiteCustomMappingId; 
			}
			
			set
			{
				if (this.entityData.SiteCustomMappingId == value)
					return;
					
				OnColumnChanging(SiteCustomMappingColumn.SiteCustomMappingId, this.entityData.SiteCustomMappingId);
				this.entityData.SiteCustomMappingId = value;
				this.EntityId.SiteCustomMappingId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteCustomMappingColumn.SiteCustomMappingId, this.entityData.SiteCustomMappingId);
				OnPropertyChanged("SiteCustomMappingId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SiteId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 SiteId
		{
			get
			{
				return this.entityData.SiteId; 
			}
			
			set
			{
				if (this.entityData.SiteId == value)
					return;
					
				OnColumnChanging(SiteCustomMappingColumn.SiteId, this.entityData.SiteId);
				this.entityData.SiteId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteCustomMappingColumn.SiteId, this.entityData.SiteId);
				OnPropertyChanged("SiteId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MasterSiteId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 MasterSiteId
		{
			get
			{
				return this.entityData.MasterSiteId; 
			}
			
			set
			{
				if (this.entityData.MasterSiteId == value)
					return;
					
				OnColumnChanging(SiteCustomMappingColumn.MasterSiteId, this.entityData.MasterSiteId);
				this.entityData.MasterSiteId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteCustomMappingColumn.MasterSiteId, this.entityData.MasterSiteId);
				OnPropertyChanged("MasterSiteId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Sites"/>.
		/// </summary>
		/// <value>The source Sites for SiteId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Sites SiteIdSource
      	{
            get { return entityData.SiteIdSource; }
            set { entityData.SiteIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "SiteCustomMapping"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"SiteCustomMappingID", "SiteID", "MasterSiteID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as SiteCustomMappingEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (SiteCustomMapping) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<SiteCustomMapping>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as SiteCustomMapping);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed SiteCustomMapping Entity 
		///</summary>
		protected virtual SiteCustomMapping Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			SiteCustomMapping copy = new SiteCustomMapping();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.SiteCustomMappingId = this.SiteCustomMappingId;
				copy.SiteId = this.SiteId;
				copy.MasterSiteId = this.MasterSiteId;
			
			if (this.SiteIdSource != null && existingCopies.Contains(this.SiteIdSource))
				copy.SiteIdSource = existingCopies[this.SiteIdSource] as Sites;
			else
				copy.SiteIdSource = MakeCopyOf(this.SiteIdSource, existingCopies) as Sites;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed SiteCustomMapping Entity 
		///</summary>
		public virtual SiteCustomMapping Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed SiteCustomMapping Entity which is a deep copy of the current entity.
		///</summary>
		public virtual SiteCustomMapping DeepCopy()
		{
			return EntityHelper.Clone<SiteCustomMapping>(this as SiteCustomMapping);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as SiteCustomMappingEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new SiteCustomMappingEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as SiteCustomMappingEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(SiteCustomMappingColumn column)
		{
			switch(column)
			{
					case SiteCustomMappingColumn.SiteCustomMappingId:
					return entityData.SiteCustomMappingId != _originalData.SiteCustomMappingId;
					case SiteCustomMappingColumn.SiteId:
					return entityData.SiteId != _originalData.SiteId;
					case SiteCustomMappingColumn.MasterSiteId:
					return entityData.MasterSiteId != _originalData.MasterSiteId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< SiteCustomMappingColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.SiteCustomMappingId != _originalData.SiteCustomMappingId;
			result = result || entityData.SiteId != _originalData.SiteId;
			result = result || entityData.MasterSiteId != _originalData.MasterSiteId;
			return result;
		}	
		
		///<summary>
		///  Returns a SiteCustomMapping Entity with the original data.
		///</summary>
		public SiteCustomMapping GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateSiteCustomMapping(
				_originalData.SiteId,
				_originalData.MasterSiteId
				);
				
			return (SiteCustomMapping)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="SiteCustomMappingBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is SiteCustomMappingBase)
				return ValueEquals(this, (SiteCustomMappingBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="SiteCustomMappingBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.SiteCustomMappingId.GetHashCode() ^ 
					this.SiteId.GetHashCode() ^ 
					this.MasterSiteId.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="SiteCustomMappingBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(SiteCustomMappingBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="SiteCustomMappingBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="SiteCustomMappingBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="SiteCustomMappingBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(SiteCustomMappingBase Object1, SiteCustomMappingBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.SiteCustomMappingId != Object2.SiteCustomMappingId)
				equal = false;
			if (Object1.SiteId != Object2.SiteId)
				equal = false;
			if (Object1.MasterSiteId != Object2.MasterSiteId)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((SiteCustomMappingBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static SiteCustomMappingComparer GetComparer()
        {
            return new SiteCustomMappingComparer();
        }
        */

        // Comparer delegates back to SiteCustomMapping
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(SiteCustomMapping rhs, SiteCustomMappingColumn which)
        {
            switch (which)
            {
            	
            	
            	case SiteCustomMappingColumn.SiteCustomMappingId:
            		return this.SiteCustomMappingId.CompareTo(rhs.SiteCustomMappingId);
            		
            		                 
            	
            	
            	case SiteCustomMappingColumn.SiteId:
            		return this.SiteId.CompareTo(rhs.SiteId);
            		
            		                 
            	
            	
            	case SiteCustomMappingColumn.MasterSiteId:
            		return this.MasterSiteId.CompareTo(rhs.MasterSiteId);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<SiteCustomMappingKey> Members
		
		// member variable for the EntityId property
		private SiteCustomMappingKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual SiteCustomMappingKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new SiteCustomMappingKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("SiteCustomMapping")
					.Append("|").Append( this.SiteCustomMappingId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- SiteCustomMappingId: {0}{3}- SiteId: {1}{3}- MasterSiteId: {2}{3}{5}", 
				this.SiteCustomMappingId,
				this.SiteId,
				this.MasterSiteId,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'SiteCustomMapping' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class SiteCustomMappingEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// SiteCustomMappingID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "SiteCustomMapping"</remarks>
		public System.Int32 SiteCustomMappingId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// SiteID : 
		/// </summary>
		public System.Int32		  SiteId = (int)0;
		
		/// <summary>
		/// MasterSiteID : 
		/// </summary>
		public System.Int32		  MasterSiteId = (int)0;
		#endregion
			
		#region Source Foreign Key Property
				
		private Sites _siteIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Sites"/>.
		/// </summary>
		/// <value>The source Sites for SiteId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Sites SiteIdSource
      	{
            get { return this._siteIdSource; }
            set { this._siteIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			SiteCustomMappingEntityData _tmp = new SiteCustomMappingEntityData();
						
			_tmp.SiteCustomMappingId = this.SiteCustomMappingId;
			
			_tmp.SiteId = this.SiteId;
			_tmp.MasterSiteId = this.MasterSiteId;
			
			#region Source Parent Composite Entities
			if (this.SiteIdSource != null)
				_tmp.SiteIdSource = MakeCopyOf(this.SiteIdSource) as Sites;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			SiteCustomMappingEntityData _tmp = new SiteCustomMappingEntityData();
						
			_tmp.SiteCustomMappingId = this.SiteCustomMappingId;
			
			_tmp.SiteId = this.SiteId;
			_tmp.MasterSiteId = this.MasterSiteId;
			
			#region Source Parent Composite Entities
			if (this.SiteIdSource != null && existingCopies.Contains(this.SiteIdSource))
				_tmp.SiteIdSource = existingCopies[this.SiteIdSource] as Sites;
			else
				_tmp.SiteIdSource = MakeCopyOf(this.SiteIdSource, existingCopies) as Sites;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SiteCustomMappingColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(SiteCustomMappingColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SiteCustomMappingColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(SiteCustomMappingColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SiteCustomMappingColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(SiteCustomMappingColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				SiteCustomMappingEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new SiteCustomMappingEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SiteCustomMappingColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(SiteCustomMappingColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				SiteCustomMappingEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new SiteCustomMappingEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region SiteCustomMappingEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="SiteCustomMapping"/> object.
	/// </remarks>
	public class SiteCustomMappingEventArgs : System.EventArgs
	{
		private SiteCustomMappingColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the SiteCustomMappingEventArgs class.
		///</summary>
		public SiteCustomMappingEventArgs(SiteCustomMappingColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the SiteCustomMappingEventArgs class.
		///</summary>
		public SiteCustomMappingEventArgs(SiteCustomMappingColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The SiteCustomMappingColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="SiteCustomMappingColumn" />
		public SiteCustomMappingColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all SiteCustomMapping related events.
	///</summary>
	public delegate void SiteCustomMappingEventHandler(object sender, SiteCustomMappingEventArgs e);
	
	#region SiteCustomMappingComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class SiteCustomMappingComparer : System.Collections.Generic.IComparer<SiteCustomMapping>
	{
		SiteCustomMappingColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:SiteCustomMappingComparer"/> class.
        /// </summary>
		public SiteCustomMappingComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:SiteCustomMappingComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public SiteCustomMappingComparer(SiteCustomMappingColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="SiteCustomMapping"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="SiteCustomMapping"/> to compare.</param>
        /// <param name="b">The second <c>SiteCustomMapping</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(SiteCustomMapping a, SiteCustomMapping b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(SiteCustomMapping entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(SiteCustomMapping a, SiteCustomMapping b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public SiteCustomMappingColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region SiteCustomMappingKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="SiteCustomMapping"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class SiteCustomMappingKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the SiteCustomMappingKey class.
		/// </summary>
		public SiteCustomMappingKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the SiteCustomMappingKey class.
		/// </summary>
		public SiteCustomMappingKey(SiteCustomMappingBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.SiteCustomMappingId = entity.SiteCustomMappingId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the SiteCustomMappingKey class.
		/// </summary>
		public SiteCustomMappingKey(System.Int32 _siteCustomMappingId)
		{
			#region Init Properties

			this.SiteCustomMappingId = _siteCustomMappingId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private SiteCustomMappingBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public SiteCustomMappingBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the SiteCustomMappingId property
		private System.Int32 _siteCustomMappingId;
		
		/// <summary>
		/// Gets or sets the SiteCustomMappingId property.
		/// </summary>
		public System.Int32 SiteCustomMappingId
		{
			get { return _siteCustomMappingId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.SiteCustomMappingId = value;
				
				_siteCustomMappingId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				SiteCustomMappingId = ( values["SiteCustomMappingId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["SiteCustomMappingId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("SiteCustomMappingId", SiteCustomMappingId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("SiteCustomMappingId: {0}{1}",
								SiteCustomMappingId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region SiteCustomMappingColumn Enum
	
	/// <summary>
	/// Enumerate the SiteCustomMapping columns.
	/// </summary>
	[Serializable]
	public enum SiteCustomMappingColumn : int
	{
		/// <summary>
		/// SiteCustomMappingId : 
		/// </summary>
		[EnumTextValue("SiteCustomMappingID")]
		[ColumnEnum("SiteCustomMappingID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		SiteCustomMappingId = 1,
		/// <summary>
		/// SiteId : 
		/// </summary>
		[EnumTextValue("SiteID")]
		[ColumnEnum("SiteID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		SiteId = 2,
		/// <summary>
		/// MasterSiteId : 
		/// </summary>
		[EnumTextValue("MasterSiteID")]
		[ColumnEnum("MasterSiteID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		MasterSiteId = 3
	}//End enum

	#endregion SiteCustomMappingColumn Enum

} // end namespace
