
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file SiteRoles.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using JXTPortal.Entities.Validation;
#endregion

namespace JXTPortal.Entities
{
	///<summary>
	/// An object representation of the 'SiteRoles' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class SiteRolesBase : EntityBase, ISiteRoles, IEntityId<SiteRolesKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private SiteRolesEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private SiteRolesEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private SiteRolesEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<SiteRoles> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SiteRolesEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SiteRolesEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="SiteRolesBase"/> instance.
		///</summary>
		public SiteRolesBase()
		{
			this.entityData = new SiteRolesEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="SiteRolesBase"/> instance.
		///</summary>
		///<param name="_siteId"></param>
		///<param name="_roleId"></param>
		///<param name="_siteRoleName"></param>
		///<param name="_valid"></param>
		///<param name="_metaTitle"></param>
		///<param name="_metaKeywords"></param>
		///<param name="_metaDescription"></param>
		///<param name="_sequence"></param>
		///<param name="_siteRoleFriendlyUrl"></param>
		///<param name="_totalJobs"></param>
		///<param name="_canonicalUrl"></param>
		public SiteRolesBase(System.Int32 _siteId, System.Int32 _roleId, System.String _siteRoleName, 
			System.Boolean _valid, System.String _metaTitle, System.String _metaKeywords, System.String _metaDescription, 
			System.Int32 _sequence, System.String _siteRoleFriendlyUrl, System.Int32 _totalJobs, System.String _canonicalUrl)
		{
			this.entityData = new SiteRolesEntityData();
			this.backupData = null;

			this.SiteId = _siteId;
			this.RoleId = _roleId;
			this.SiteRoleName = _siteRoleName;
			this.Valid = _valid;
			this.MetaTitle = _metaTitle;
			this.MetaKeywords = _metaKeywords;
			this.MetaDescription = _metaDescription;
			this.Sequence = _sequence;
			this.SiteRoleFriendlyUrl = _siteRoleFriendlyUrl;
			this.TotalJobs = _totalJobs;
			this.CanonicalUrl = _canonicalUrl;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="SiteRoles"/> instance.
		///</summary>
		///<param name="_siteId"></param>
		///<param name="_roleId"></param>
		///<param name="_siteRoleName"></param>
		///<param name="_valid"></param>
		///<param name="_metaTitle"></param>
		///<param name="_metaKeywords"></param>
		///<param name="_metaDescription"></param>
		///<param name="_sequence"></param>
		///<param name="_siteRoleFriendlyUrl"></param>
		///<param name="_totalJobs"></param>
		///<param name="_canonicalUrl"></param>
		public static SiteRoles CreateSiteRoles(System.Int32 _siteId, System.Int32 _roleId, System.String _siteRoleName, 
			System.Boolean _valid, System.String _metaTitle, System.String _metaKeywords, System.String _metaDescription, 
			System.Int32 _sequence, System.String _siteRoleFriendlyUrl, System.Int32 _totalJobs, System.String _canonicalUrl)
		{
			SiteRoles newSiteRoles = new SiteRoles();
			newSiteRoles.SiteId = _siteId;
			newSiteRoles.RoleId = _roleId;
			newSiteRoles.SiteRoleName = _siteRoleName;
			newSiteRoles.Valid = _valid;
			newSiteRoles.MetaTitle = _metaTitle;
			newSiteRoles.MetaKeywords = _metaKeywords;
			newSiteRoles.MetaDescription = _metaDescription;
			newSiteRoles.Sequence = _sequence;
			newSiteRoles.SiteRoleFriendlyUrl = _siteRoleFriendlyUrl;
			newSiteRoles.TotalJobs = _totalJobs;
			newSiteRoles.CanonicalUrl = _canonicalUrl;
			return newSiteRoles;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the SiteRoleId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 SiteRoleId
		{
			get
			{
				return this.entityData.SiteRoleId; 
			}
			
			set
			{
				if (this.entityData.SiteRoleId == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.SiteRoleId, this.entityData.SiteRoleId);
				this.entityData.SiteRoleId = value;
				this.EntityId.SiteRoleId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.SiteRoleId, this.entityData.SiteRoleId);
				OnPropertyChanged("SiteRoleId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SiteId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 SiteId
		{
			get
			{
				return this.entityData.SiteId; 
			}
			
			set
			{
				if (this.entityData.SiteId == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.SiteId, this.entityData.SiteId);
				this.entityData.SiteId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.SiteId, this.entityData.SiteId);
				OnPropertyChanged("SiteId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the RoleId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 RoleId
		{
			get
			{
				return this.entityData.RoleId; 
			}
			
			set
			{
				if (this.entityData.RoleId == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.RoleId, this.entityData.RoleId);
				this.entityData.RoleId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.RoleId, this.entityData.RoleId);
				OnPropertyChanged("RoleId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SiteRoleName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1020)]
		public virtual System.String SiteRoleName
		{
			get
			{
				return this.entityData.SiteRoleName; 
			}
			
			set
			{
				if (this.entityData.SiteRoleName == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.SiteRoleName, this.entityData.SiteRoleName);
				this.entityData.SiteRoleName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.SiteRoleName, this.entityData.SiteRoleName);
				OnPropertyChanged("SiteRoleName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Valid property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Boolean Valid
		{
			get
			{
				return this.entityData.Valid; 
			}
			
			set
			{
				if (this.entityData.Valid == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.Valid, this.entityData.Valid);
				this.entityData.Valid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.Valid, this.entityData.Valid);
				OnPropertyChanged("Valid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MetaTitle property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 255)]
		public virtual System.String MetaTitle
		{
			get
			{
				return this.entityData.MetaTitle; 
			}
			
			set
			{
				if (this.entityData.MetaTitle == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.MetaTitle, this.entityData.MetaTitle);
				this.entityData.MetaTitle = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.MetaTitle, this.entityData.MetaTitle);
				OnPropertyChanged("MetaTitle");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MetaKeywords property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 255)]
		public virtual System.String MetaKeywords
		{
			get
			{
				return this.entityData.MetaKeywords; 
			}
			
			set
			{
				if (this.entityData.MetaKeywords == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.MetaKeywords, this.entityData.MetaKeywords);
				this.entityData.MetaKeywords = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.MetaKeywords, this.entityData.MetaKeywords);
				OnPropertyChanged("MetaKeywords");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MetaDescription property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 512)]
		public virtual System.String MetaDescription
		{
			get
			{
				return this.entityData.MetaDescription; 
			}
			
			set
			{
				if (this.entityData.MetaDescription == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.MetaDescription, this.entityData.MetaDescription);
				this.entityData.MetaDescription = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.MetaDescription, this.entityData.MetaDescription);
				OnPropertyChanged("MetaDescription");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Sequence property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Sequence
		{
			get
			{
				return this.entityData.Sequence; 
			}
			
			set
			{
				if (this.entityData.Sequence == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.Sequence, this.entityData.Sequence);
				this.entityData.Sequence = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.Sequence, this.entityData.Sequence);
				OnPropertyChanged("Sequence");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SiteRoleFriendlyUrl property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 255)]
		public virtual System.String SiteRoleFriendlyUrl
		{
			get
			{
				return this.entityData.SiteRoleFriendlyUrl; 
			}
			
			set
			{
				if (this.entityData.SiteRoleFriendlyUrl == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.SiteRoleFriendlyUrl, this.entityData.SiteRoleFriendlyUrl);
				this.entityData.SiteRoleFriendlyUrl = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.SiteRoleFriendlyUrl, this.entityData.SiteRoleFriendlyUrl);
				OnPropertyChanged("SiteRoleFriendlyUrl");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TotalJobs property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 TotalJobs
		{
			get
			{
				return this.entityData.TotalJobs; 
			}
			
			set
			{
				if (this.entityData.TotalJobs == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.TotalJobs, this.entityData.TotalJobs);
				this.entityData.TotalJobs = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.TotalJobs, this.entityData.TotalJobs);
				OnPropertyChanged("TotalJobs");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CanonicalUrl property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 255)]
		public virtual System.String CanonicalUrl
		{
			get
			{
				return this.entityData.CanonicalUrl; 
			}
			
			set
			{
				if (this.entityData.CanonicalUrl == value)
					return;
					
				OnColumnChanging(SiteRolesColumn.CanonicalUrl, this.entityData.CanonicalUrl);
				this.entityData.CanonicalUrl = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SiteRolesColumn.CanonicalUrl, this.entityData.CanonicalUrl);
				OnPropertyChanged("CanonicalUrl");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Roles"/>.
		/// </summary>
		/// <value>The source Roles for RoleId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Roles RoleIdSource
      	{
            get { return entityData.RoleIdSource; }
            set { entityData.RoleIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Sites"/>.
		/// </summary>
		/// <value>The source Sites for SiteId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Sites SiteIdSource
      	{
            get { return entityData.SiteIdSource; }
            set { entityData.SiteIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("SiteRoleName", "Site Role Name", 1020));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("MetaTitle", "Meta Title"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("MetaTitle", "Meta Title", 255));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("MetaKeywords", "Meta Keywords"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("MetaKeywords", "Meta Keywords", 255));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("MetaDescription", "Meta Description"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("MetaDescription", "Meta Description", 512));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("SiteRoleFriendlyUrl", "Site Role Friendly Url", 255));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("CanonicalUrl", "Canonical Url", 255));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "SiteRoles"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"SiteRoleID", "SiteID", "RoleID", "SiteRoleName", "Valid", "MetaTitle", "MetaKeywords", "MetaDescription", "Sequence", "SiteRoleFriendlyUrl", "TotalJobs", "CanonicalUrl"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as SiteRolesEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (SiteRoles) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<SiteRoles>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as SiteRoles);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed SiteRoles Entity 
		///</summary>
		protected virtual SiteRoles Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			SiteRoles copy = new SiteRoles();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.SiteRoleId = this.SiteRoleId;
				copy.SiteId = this.SiteId;
				copy.RoleId = this.RoleId;
				copy.SiteRoleName = this.SiteRoleName;
				copy.Valid = this.Valid;
				copy.MetaTitle = this.MetaTitle;
				copy.MetaKeywords = this.MetaKeywords;
				copy.MetaDescription = this.MetaDescription;
				copy.Sequence = this.Sequence;
				copy.SiteRoleFriendlyUrl = this.SiteRoleFriendlyUrl;
				copy.TotalJobs = this.TotalJobs;
				copy.CanonicalUrl = this.CanonicalUrl;
			
			if (this.RoleIdSource != null && existingCopies.Contains(this.RoleIdSource))
				copy.RoleIdSource = existingCopies[this.RoleIdSource] as Roles;
			else
				copy.RoleIdSource = MakeCopyOf(this.RoleIdSource, existingCopies) as Roles;
			if (this.SiteIdSource != null && existingCopies.Contains(this.SiteIdSource))
				copy.SiteIdSource = existingCopies[this.SiteIdSource] as Sites;
			else
				copy.SiteIdSource = MakeCopyOf(this.SiteIdSource, existingCopies) as Sites;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed SiteRoles Entity 
		///</summary>
		public virtual SiteRoles Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed SiteRoles Entity which is a deep copy of the current entity.
		///</summary>
		public virtual SiteRoles DeepCopy()
		{
			return EntityHelper.Clone<SiteRoles>(this as SiteRoles);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as SiteRolesEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new SiteRolesEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as SiteRolesEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(SiteRolesColumn column)
		{
			switch(column)
			{
					case SiteRolesColumn.SiteRoleId:
					return entityData.SiteRoleId != _originalData.SiteRoleId;
					case SiteRolesColumn.SiteId:
					return entityData.SiteId != _originalData.SiteId;
					case SiteRolesColumn.RoleId:
					return entityData.RoleId != _originalData.RoleId;
					case SiteRolesColumn.SiteRoleName:
					return entityData.SiteRoleName != _originalData.SiteRoleName;
					case SiteRolesColumn.Valid:
					return entityData.Valid != _originalData.Valid;
					case SiteRolesColumn.MetaTitle:
					return entityData.MetaTitle != _originalData.MetaTitle;
					case SiteRolesColumn.MetaKeywords:
					return entityData.MetaKeywords != _originalData.MetaKeywords;
					case SiteRolesColumn.MetaDescription:
					return entityData.MetaDescription != _originalData.MetaDescription;
					case SiteRolesColumn.Sequence:
					return entityData.Sequence != _originalData.Sequence;
					case SiteRolesColumn.SiteRoleFriendlyUrl:
					return entityData.SiteRoleFriendlyUrl != _originalData.SiteRoleFriendlyUrl;
					case SiteRolesColumn.TotalJobs:
					return entityData.TotalJobs != _originalData.TotalJobs;
					case SiteRolesColumn.CanonicalUrl:
					return entityData.CanonicalUrl != _originalData.CanonicalUrl;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< SiteRolesColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.SiteRoleId != _originalData.SiteRoleId;
			result = result || entityData.SiteId != _originalData.SiteId;
			result = result || entityData.RoleId != _originalData.RoleId;
			result = result || entityData.SiteRoleName != _originalData.SiteRoleName;
			result = result || entityData.Valid != _originalData.Valid;
			result = result || entityData.MetaTitle != _originalData.MetaTitle;
			result = result || entityData.MetaKeywords != _originalData.MetaKeywords;
			result = result || entityData.MetaDescription != _originalData.MetaDescription;
			result = result || entityData.Sequence != _originalData.Sequence;
			result = result || entityData.SiteRoleFriendlyUrl != _originalData.SiteRoleFriendlyUrl;
			result = result || entityData.TotalJobs != _originalData.TotalJobs;
			result = result || entityData.CanonicalUrl != _originalData.CanonicalUrl;
			return result;
		}	
		
		///<summary>
		///  Returns a SiteRoles Entity with the original data.
		///</summary>
		public SiteRoles GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateSiteRoles(
				_originalData.SiteId,
				_originalData.RoleId,
				_originalData.SiteRoleName,
				_originalData.Valid,
				_originalData.MetaTitle,
				_originalData.MetaKeywords,
				_originalData.MetaDescription,
				_originalData.Sequence,
				_originalData.SiteRoleFriendlyUrl,
				_originalData.TotalJobs,
				_originalData.CanonicalUrl
				);
				
			return (SiteRoles)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="SiteRolesBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is SiteRolesBase)
				return ValueEquals(this, (SiteRolesBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="SiteRolesBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.SiteRoleId.GetHashCode() ^ 
					this.SiteId.GetHashCode() ^ 
					this.RoleId.GetHashCode() ^ 
					((this.SiteRoleName == null) ? string.Empty : this.SiteRoleName.ToString()).GetHashCode() ^ 
					this.Valid.GetHashCode() ^ 
					this.MetaTitle.GetHashCode() ^ 
					this.MetaKeywords.GetHashCode() ^ 
					this.MetaDescription.GetHashCode() ^ 
					this.Sequence.GetHashCode() ^ 
					((this.SiteRoleFriendlyUrl == null) ? string.Empty : this.SiteRoleFriendlyUrl.ToString()).GetHashCode() ^ 
					this.TotalJobs.GetHashCode() ^ 
					((this.CanonicalUrl == null) ? string.Empty : this.CanonicalUrl.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="SiteRolesBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(SiteRolesBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="SiteRolesBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="SiteRolesBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="SiteRolesBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(SiteRolesBase Object1, SiteRolesBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.SiteRoleId != Object2.SiteRoleId)
				equal = false;
			if (Object1.SiteId != Object2.SiteId)
				equal = false;
			if (Object1.RoleId != Object2.RoleId)
				equal = false;
			if ( Object1.SiteRoleName != null && Object2.SiteRoleName != null )
			{
				if (Object1.SiteRoleName != Object2.SiteRoleName)
					equal = false;
			}
			else if (Object1.SiteRoleName == null ^ Object2.SiteRoleName == null )
			{
				equal = false;
			}
			if (Object1.Valid != Object2.Valid)
				equal = false;
			if (Object1.MetaTitle != Object2.MetaTitle)
				equal = false;
			if (Object1.MetaKeywords != Object2.MetaKeywords)
				equal = false;
			if (Object1.MetaDescription != Object2.MetaDescription)
				equal = false;
			if (Object1.Sequence != Object2.Sequence)
				equal = false;
			if ( Object1.SiteRoleFriendlyUrl != null && Object2.SiteRoleFriendlyUrl != null )
			{
				if (Object1.SiteRoleFriendlyUrl != Object2.SiteRoleFriendlyUrl)
					equal = false;
			}
			else if (Object1.SiteRoleFriendlyUrl == null ^ Object2.SiteRoleFriendlyUrl == null )
			{
				equal = false;
			}
			if (Object1.TotalJobs != Object2.TotalJobs)
				equal = false;
			if ( Object1.CanonicalUrl != null && Object2.CanonicalUrl != null )
			{
				if (Object1.CanonicalUrl != Object2.CanonicalUrl)
					equal = false;
			}
			else if (Object1.CanonicalUrl == null ^ Object2.CanonicalUrl == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((SiteRolesBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static SiteRolesComparer GetComparer()
        {
            return new SiteRolesComparer();
        }
        */

        // Comparer delegates back to SiteRoles
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(SiteRoles rhs, SiteRolesColumn which)
        {
            switch (which)
            {
            	
            	
            	case SiteRolesColumn.SiteRoleId:
            		return this.SiteRoleId.CompareTo(rhs.SiteRoleId);
            		
            		                 
            	
            	
            	case SiteRolesColumn.SiteId:
            		return this.SiteId.CompareTo(rhs.SiteId);
            		
            		                 
            	
            	
            	case SiteRolesColumn.RoleId:
            		return this.RoleId.CompareTo(rhs.RoleId);
            		
            		                 
            	
            	
            	case SiteRolesColumn.SiteRoleName:
            		return this.SiteRoleName.CompareTo(rhs.SiteRoleName);
            		
            		                 
            	
            	
            	case SiteRolesColumn.Valid:
            		return this.Valid.CompareTo(rhs.Valid);
            		
            		                 
            	
            	
            	case SiteRolesColumn.MetaTitle:
            		return this.MetaTitle.CompareTo(rhs.MetaTitle);
            		
            		                 
            	
            	
            	case SiteRolesColumn.MetaKeywords:
            		return this.MetaKeywords.CompareTo(rhs.MetaKeywords);
            		
            		                 
            	
            	
            	case SiteRolesColumn.MetaDescription:
            		return this.MetaDescription.CompareTo(rhs.MetaDescription);
            		
            		                 
            	
            	
            	case SiteRolesColumn.Sequence:
            		return this.Sequence.CompareTo(rhs.Sequence);
            		
            		                 
            	
            	
            	case SiteRolesColumn.SiteRoleFriendlyUrl:
            		return this.SiteRoleFriendlyUrl.CompareTo(rhs.SiteRoleFriendlyUrl);
            		
            		                 
            	
            	
            	case SiteRolesColumn.TotalJobs:
            		return this.TotalJobs.CompareTo(rhs.TotalJobs);
            		
            		                 
            	
            	
            	case SiteRolesColumn.CanonicalUrl:
            		return this.CanonicalUrl.CompareTo(rhs.CanonicalUrl);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<SiteRolesKey> Members
		
		// member variable for the EntityId property
		private SiteRolesKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual SiteRolesKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new SiteRolesKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("SiteRoles")
					.Append("|").Append( this.SiteRoleId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{13}{12}- SiteRoleId: {0}{12}- SiteId: {1}{12}- RoleId: {2}{12}- SiteRoleName: {3}{12}- Valid: {4}{12}- MetaTitle: {5}{12}- MetaKeywords: {6}{12}- MetaDescription: {7}{12}- Sequence: {8}{12}- SiteRoleFriendlyUrl: {9}{12}- TotalJobs: {10}{12}- CanonicalUrl: {11}{12}{14}", 
				this.SiteRoleId,
				this.SiteId,
				this.RoleId,
				(this.SiteRoleName == null) ? string.Empty : this.SiteRoleName.ToString(),
				this.Valid,
				this.MetaTitle,
				this.MetaKeywords,
				this.MetaDescription,
				this.Sequence,
				(this.SiteRoleFriendlyUrl == null) ? string.Empty : this.SiteRoleFriendlyUrl.ToString(),
				this.TotalJobs,
				(this.CanonicalUrl == null) ? string.Empty : this.CanonicalUrl.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'SiteRoles' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class SiteRolesEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// SiteRoleID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "SiteRoles"</remarks>
		public System.Int32 SiteRoleId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// SiteID : 
		/// </summary>
		public System.Int32		  SiteId = (int)0;
		
		/// <summary>
		/// RoleID : 
		/// </summary>
		public System.Int32		  RoleId = (int)0;
		
		/// <summary>
		/// SiteRoleName : 
		/// </summary>
		public System.String		  SiteRoleName = null;
		
		/// <summary>
		/// Valid : 
		/// </summary>
		public System.Boolean		  Valid = false;
		
		/// <summary>
		/// MetaTitle : 
		/// </summary>
		public System.String		  MetaTitle = string.Empty;
		
		/// <summary>
		/// MetaKeywords : 
		/// </summary>
		public System.String		  MetaKeywords = string.Empty;
		
		/// <summary>
		/// MetaDescription : 
		/// </summary>
		public System.String		  MetaDescription = string.Empty;
		
		/// <summary>
		/// Sequence : 
		/// </summary>
		public System.Int32		  Sequence = (int)0;
		
		/// <summary>
		/// SiteRoleFriendlyUrl : 
		/// </summary>
		public System.String		  SiteRoleFriendlyUrl = null;
		
		/// <summary>
		/// TotalJobs : 
		/// </summary>
		public System.Int32		  TotalJobs = (int)0;
		
		/// <summary>
		/// CanonicalUrl : 
		/// </summary>
		public System.String		  CanonicalUrl = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Roles _roleIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Roles"/>.
		/// </summary>
		/// <value>The source Roles for RoleId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Roles RoleIdSource
      	{
            get { return this._roleIdSource; }
            set { this._roleIdSource = value; }
      	}
		private Sites _siteIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Sites"/>.
		/// </summary>
		/// <value>The source Sites for SiteId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Sites SiteIdSource
      	{
            get { return this._siteIdSource; }
            set { this._siteIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			SiteRolesEntityData _tmp = new SiteRolesEntityData();
						
			_tmp.SiteRoleId = this.SiteRoleId;
			
			_tmp.SiteId = this.SiteId;
			_tmp.RoleId = this.RoleId;
			_tmp.SiteRoleName = this.SiteRoleName;
			_tmp.Valid = this.Valid;
			_tmp.MetaTitle = this.MetaTitle;
			_tmp.MetaKeywords = this.MetaKeywords;
			_tmp.MetaDescription = this.MetaDescription;
			_tmp.Sequence = this.Sequence;
			_tmp.SiteRoleFriendlyUrl = this.SiteRoleFriendlyUrl;
			_tmp.TotalJobs = this.TotalJobs;
			_tmp.CanonicalUrl = this.CanonicalUrl;
			
			#region Source Parent Composite Entities
			if (this.RoleIdSource != null)
				_tmp.RoleIdSource = MakeCopyOf(this.RoleIdSource) as Roles;
			if (this.SiteIdSource != null)
				_tmp.SiteIdSource = MakeCopyOf(this.SiteIdSource) as Sites;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			SiteRolesEntityData _tmp = new SiteRolesEntityData();
						
			_tmp.SiteRoleId = this.SiteRoleId;
			
			_tmp.SiteId = this.SiteId;
			_tmp.RoleId = this.RoleId;
			_tmp.SiteRoleName = this.SiteRoleName;
			_tmp.Valid = this.Valid;
			_tmp.MetaTitle = this.MetaTitle;
			_tmp.MetaKeywords = this.MetaKeywords;
			_tmp.MetaDescription = this.MetaDescription;
			_tmp.Sequence = this.Sequence;
			_tmp.SiteRoleFriendlyUrl = this.SiteRoleFriendlyUrl;
			_tmp.TotalJobs = this.TotalJobs;
			_tmp.CanonicalUrl = this.CanonicalUrl;
			
			#region Source Parent Composite Entities
			if (this.RoleIdSource != null && existingCopies.Contains(this.RoleIdSource))
				_tmp.RoleIdSource = existingCopies[this.RoleIdSource] as Roles;
			else
				_tmp.RoleIdSource = MakeCopyOf(this.RoleIdSource, existingCopies) as Roles;
			if (this.SiteIdSource != null && existingCopies.Contains(this.SiteIdSource))
				_tmp.SiteIdSource = existingCopies[this.SiteIdSource] as Sites;
			else
				_tmp.SiteIdSource = MakeCopyOf(this.SiteIdSource, existingCopies) as Sites;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SiteRolesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(SiteRolesColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SiteRolesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(SiteRolesColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SiteRolesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(SiteRolesColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				SiteRolesEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new SiteRolesEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SiteRolesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(SiteRolesColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				SiteRolesEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new SiteRolesEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region SiteRolesEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="SiteRoles"/> object.
	/// </remarks>
	public class SiteRolesEventArgs : System.EventArgs
	{
		private SiteRolesColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the SiteRolesEventArgs class.
		///</summary>
		public SiteRolesEventArgs(SiteRolesColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the SiteRolesEventArgs class.
		///</summary>
		public SiteRolesEventArgs(SiteRolesColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The SiteRolesColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="SiteRolesColumn" />
		public SiteRolesColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all SiteRoles related events.
	///</summary>
	public delegate void SiteRolesEventHandler(object sender, SiteRolesEventArgs e);
	
	#region SiteRolesComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class SiteRolesComparer : System.Collections.Generic.IComparer<SiteRoles>
	{
		SiteRolesColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:SiteRolesComparer"/> class.
        /// </summary>
		public SiteRolesComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:SiteRolesComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public SiteRolesComparer(SiteRolesColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="SiteRoles"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="SiteRoles"/> to compare.</param>
        /// <param name="b">The second <c>SiteRoles</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(SiteRoles a, SiteRoles b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(SiteRoles entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(SiteRoles a, SiteRoles b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public SiteRolesColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region SiteRolesKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="SiteRoles"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class SiteRolesKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the SiteRolesKey class.
		/// </summary>
		public SiteRolesKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the SiteRolesKey class.
		/// </summary>
		public SiteRolesKey(SiteRolesBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.SiteRoleId = entity.SiteRoleId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the SiteRolesKey class.
		/// </summary>
		public SiteRolesKey(System.Int32 _siteRoleId)
		{
			#region Init Properties

			this.SiteRoleId = _siteRoleId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private SiteRolesBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public SiteRolesBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the SiteRoleId property
		private System.Int32 _siteRoleId;
		
		/// <summary>
		/// Gets or sets the SiteRoleId property.
		/// </summary>
		public System.Int32 SiteRoleId
		{
			get { return _siteRoleId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.SiteRoleId = value;
				
				_siteRoleId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				SiteRoleId = ( values["SiteRoleId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["SiteRoleId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("SiteRoleId", SiteRoleId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("SiteRoleId: {0}{1}",
								SiteRoleId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region SiteRolesColumn Enum
	
	/// <summary>
	/// Enumerate the SiteRoles columns.
	/// </summary>
	[Serializable]
	public enum SiteRolesColumn : int
	{
		/// <summary>
		/// SiteRoleId : 
		/// </summary>
		[EnumTextValue("SiteRoleID")]
		[ColumnEnum("SiteRoleID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		SiteRoleId = 1,
		/// <summary>
		/// SiteId : 
		/// </summary>
		[EnumTextValue("SiteID")]
		[ColumnEnum("SiteID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		SiteId = 2,
		/// <summary>
		/// RoleId : 
		/// </summary>
		[EnumTextValue("RoleID")]
		[ColumnEnum("RoleID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		RoleId = 3,
		/// <summary>
		/// SiteRoleName : 
		/// </summary>
		[EnumTextValue("SiteRoleName")]
		[ColumnEnum("SiteRoleName", typeof(System.String), System.Data.DbType.String, false, false, true, 1020)]
		SiteRoleName = 4,
		/// <summary>
		/// Valid : 
		/// </summary>
		[EnumTextValue("Valid")]
		[ColumnEnum("Valid", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		Valid = 5,
		/// <summary>
		/// MetaTitle : 
		/// </summary>
		[EnumTextValue("MetaTitle")]
		[ColumnEnum("MetaTitle", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 255)]
		MetaTitle = 6,
		/// <summary>
		/// MetaKeywords : 
		/// </summary>
		[EnumTextValue("MetaKeywords")]
		[ColumnEnum("MetaKeywords", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 255)]
		MetaKeywords = 7,
		/// <summary>
		/// MetaDescription : 
		/// </summary>
		[EnumTextValue("MetaDescription")]
		[ColumnEnum("MetaDescription", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 512)]
		MetaDescription = 8,
		/// <summary>
		/// Sequence : 
		/// </summary>
		[EnumTextValue("Sequence")]
		[ColumnEnum("Sequence", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Sequence = 9,
		/// <summary>
		/// SiteRoleFriendlyUrl : 
		/// </summary>
		[EnumTextValue("SiteRoleFriendlyUrl")]
		[ColumnEnum("SiteRoleFriendlyUrl", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 255)]
		SiteRoleFriendlyUrl = 10,
		/// <summary>
		/// TotalJobs : 
		/// </summary>
		[EnumTextValue("TotalJobs")]
		[ColumnEnum("TotalJobs", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		TotalJobs = 11,
		/// <summary>
		/// CanonicalUrl : 
		/// </summary>
		[EnumTextValue("CanonicalUrl")]
		[ColumnEnum("CanonicalUrl", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 255)]
		CanonicalUrl = 12
	}//End enum

	#endregion SiteRolesColumn Enum

} // end namespace
