  
CREATE PROCEDURE ViewJobs_GetByID        
 @JobID INT,    
 @SiteID INT        
AS        
SELECT [JobID]        
      ,[SiteID]        
      ,[WorkTypeID]        
      ,[SalaryID]        
      ,[JobName]        
      ,[Description]        
      ,[FullDescription]        
      ,[WebServiceProcessed]        
      ,[ApplicationEmailAddress]        
      ,[RefNo]        
      ,[Visible]        
      ,[DatePosted]        
      ,[ExpiryDate]        
      ,[Expired]        
      ,[JobItemPrice]        
      ,[Billed]        
      ,[LastModified]        
      ,[ShowSalaryDetails]        
      ,[SalaryText]        
      ,[ViewJobs].[AdvertiserID]        
      ,[LastModifiedByAdvertiserUserId]        
      ,[LastModifiedByAdminUserId]        
      ,[JobItemTypeID]        
      ,[ApplicationMethod]        
      ,[ApplicationURL]        
      ,[UploadMethod]        
      ,[Tags]        
      ,[JobTemplateID]        
      ,[SearchField]        
      ,[AdvertiserJobTemplateLogoID]        
      ,[CompanyName]        
      ,[HashValue]        
      ,[RequireLogonForExternalApplications]        
      ,[ShowLocationDetails]        
      ,[PublicTransport]        
      ,[Address]        
      ,[ContactDetails]        
      ,[JobContactPhone]        
      ,[JobContactName]        
      ,[QualificationsRecognised]        
      ,[ResidentOnly]        
      ,[DocumentLink]        
      ,[BulletPoint1]        
      ,[BulletPoint2]        
      ,[BulletPoint3]        
      ,[HotJob]        
      ,[AdvertiserCompanyName]        
      ,[BusinessNumber]        
      ,[StreetAddress1]        
      ,[StreetAddress2]        
      ,[WebAddress]        
      ,[Profile]        
      ,[RequireLogonForExternalApplication]        
      ,[AdvertiserLogo]        
      ,[SiteWorkTypeName]        
      ,[SiteSalaryName]        
      ,[SalaryUpperBand]        
      ,[SalaryLowerBand]        
      ,[JobTemplateHTML]        
      ,[SalaryTypeName]        
      ,[SiteAreaName]        
      ,[SiteLocationName]        
      ,[SiteRoleName]        
      ,[SiteProfessionName]      
   ,[JobFriendlyName]  
   ,[ProfessionID]  
   ,[RoleID]  
  FROM [dbo].[udfSite_GetAdvertisers](@SiteID) AdvertiserFilter    
  INNER JOIN [dbo].[ViewJobs] ON ViewJobs.AdvertiserID =  AdvertiserFilter.AdvertiserID       
  WHERE [JobID] = @JobID      
      